[project]
name = "capturesmiles"
version = "0.1.0"
description = "detection of smiles from camera feed and take picture of it"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python",
    "rich",
    "ultralytics",
]
